### ISSUE TITLE
[LOGIC] Fill score starter sheet on editing

### ISSUE THREAD

**Issue by dmitrychaban** [scorsero/scorsero-client-android#9]
### Abilities:
1. User can long-click on item to open score starter screen
2. Score starter must be pre-filled with current data of the score
3. When score starter screen opens, fab is a remove button with trash basket icon
4. When user starts editing, fab icon changes to save button with check icon

#### Update:
* User cannot remove any score permanently from main screen
* To remove score user needs to open Score creation screen

**Comment by dmi3coder** [comment]
As of #14 long click will open ScoreCreationController

**Comment by dmi3coder** [comment]
#### Update:
* User cannot remove any score permanently from main screen
* To remove score user needs to open Score creation screen
